# Generated by Django 4.1.2 on 2022-11-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_owner_auction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='owner',
        ),
    ]
